{% set version = "1.5" %}
{% set sha256 = "7c7091e9c86196148bd41177b4590dccb1510bfe6cea5bf7407ff194482eb049" %}

package:
  name: libftdi
  version: '{{ version }}'

source:
  fn:   libftdi1-{{ version }}.tar.bz2
  url:  https://www.intra2net.com/en/developer/libftdi/download/libftdi1-{{ version }}.tar.bz2
  sha256: '{{ sha256 }}'
  patches:
    - use_libusb_pkgconfig.patch
    - fix_win_build.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkgconfig
  host:
    - libusb

test:
  commands:
    - test -f ${PREFIX}/include/libftdi1/ftdi.h                  # [unix]
    - test -f ${PREFIX}/lib/libftdi1${SHLIB_EXT}                 # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libftdi1.pc                # [unix]
    - test -f ${PREFIX}/lib/cmake/libftdi1/LibFTDI1Config.cmake  # [unix]
    - if not exist %LIBRARY_INC%\libftdi1\ftdi.h (exit 1)        # [win]
    # - if not exist %LIBRARY_LIB%\libftdi1.lib (exit 1)           # [win]
    - if not exist %LIBRARY_BIN%\libftdi1.dll (exit 1)           # [win]

about:
  home: https://www.intra2net.com/en/developer/libftdi/
  license: LGPL-2.1-or-later
  summary: 'FTDI USB driver with bitbang mode'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
